### ISSUE TITLE
Requiring each function

### ISSUE THREAD

**Issue by jackbridger** [fac-17/SaVaGe#33]
When you do:

const getAllDataQuery = require("./queries/getAllDataquery");
const getSVGsQuery = require("./queries/getSVGsquery");
const postSVGquery = require("./queries/postSVGquery");
const postSHAPEquery = require("./queries/postSHAPEquery");
const getSHAPEsquery = require("./queries/getSHAPEsquery");
const insertSVG_SHAPEquery= require("./queries/post_SVG_SHAPE");

You can do create a file in queries called index.js and inside put:

module.exports = {
  getAllDataQuery: require("./queries/getAllDataquery"),
  getSVGsQuery = require("./queries/getSVGsquery")
};

Then you can require the whole directory require('./queries);

Then just do queries.getAllDataQuery() etc.

See below: 

https://stackoverflow.com/questions/37417422/nodejs-good-practice-to-just-use-the-index-js-to-exports

**Comment by crianonim** [comment]
Good point! Thanks!
