### ISSUE TITLE
Cool modularisation in queries (?)

### ISSUE THREAD

**Issue by Albadylic** [fac-17/SaVaGe#63]
Very cool that each query has its own file! :+1: 

You have a file (index.js) which exports all the modules in the queries folder. I tried to work out where this file was called but I couldn't work it out. :confused:  Could you talk about this in your presentation?

**Comment by crianonim** [comment]
See our last week issue #33

**Comment by Albadylic** [comment]
Cool, thanks @crianonim , @jackbridger !
