### ISSUE TITLE
Cursor: pointer on input field

### ISSUE THREAD

**Issue by georgiamshaw** [fac-17/SaVaGe#64]
You've got cursor: pointer on your input fields, but this probably isn't best practice because it's not a button, so it's misleading for the user. 

<img width="729" alt="Screenshot 2019-08-16 at 10 21 06" src="https://user-images.githubusercontent.com/36238916/63157824-c265ba80-c00f-11e9-8714-944022eaba51.png">

You've also got your login button black on hover - perhaps another way of showing hover would be better for accessibility?

<img width="1440" alt="Screenshot 2019-08-16 at 10 22 59" src="https://user-images.githubusercontent.com/36238916/63157855-d7424e00-c00f-11e9-8ba0-ea6bacac64ee.png">

**Comment by crianonim** [comment]
Thanks for that Georgia! Wonderful feedback! :fireworks:
