### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by gminova** [fac-17/SaVaGe#70]
when I check endpoin /getAllData I have unrestricted access to your database and all the user's info without being logged in

![Screenshot from 2019-08-16 10-42-54](https://user-images.githubusercontent.com/42014388/63159202-d3fc9180-c012-11e9-8d44-ecad50287959.png)

**Comment by crianonim** [comment]
This is on purpose! It's a feature! Gallery is public, not restricted
