### ISSUE TITLE
Server-side validation

### ISSUE THREAD

**Issue by bobbysebolao** [fac-17/SaVaGe#79]
Great job implementing client-side validation checks and providing descriptive feedback for your users!

It’s worth bearing in mind that, while client side validation can enhance the user experience, it isn’t considered secure.

For future reference, it’s a good idea to repeat regex pattern matching checks on the server side too. Currently, if somebody wanted to bypass your form input regex requirements, they could do so quite easily by removing the HTML ```required``` attribute in their browser’s console.

**Comment by crianonim** [comment]
Thanks! We def need to implement proper front and back end validation, it's one of our stretch goals!
